calstates4/s4-shared-components

src/components/02-components/cta-card/cta-card.stories.tsx
src/components/02-components/cta-card/cta-card.tsx
src/index.ts
src/theme/index.ts

- [CSU-291](https://app.clickup.com/t/36718269/CSU-291)
- Create new component CTA card
- Go to [CTA card ](http://localhost:6006/?path=/story/components-cta-card--default)
- Check that it looks like the [design](https://www.figma.com/file/Lh3hcoB0HXskHC6YllGIZM/CSU-S4-Client-Reviews?type=design&node-id=370-32303&t=BbhPR4GCcHa4UpVA-0)
In this PR, the headings sizes were overwritten.

CSU-291: New student dashboard

---

package-lock.json
package.json
src/components/02-components/brand/brand.stories.tsx
src/components/02-components/brand/brand.tsx
src/components/02-components/context/context.stories.tsx
src/components/02-components/context/context.tsx

[CSU-304](https://app.clickup.com/t/36718269/CSU-304)
- Update brand and context components to make them more generic - needed for Partners site.

CSU-304: Update context & brand components

---

.github/PULL_REQUEST_TEMPLATE.md
.storybook/preview-head.html
.storybook/preview.tsx
package-lock.json
package.json
src/components/01-elements/breadcrumbs/breadcrumbs.stories.tsx
src/components/01-elements/breadcrumbs/breadcrumbs.tsx
src/components/01-elements/pager/pager.stories.tsx
src/components/01-elements/pager/pager.tsx
src/components/02-components/brand/brand.tsx
src/components/02-components/main-content/main-content.tsx
src/components/02-components/organization-page/organization-page.stories.tsx
src/components/02-components/organization-page/organization-page.tsx
src/components/03-layouts/page-layout/page-layout.stories.tsx
src/index.ts
src/theme/index.ts

- Create Organization page, pager and breadcrumbs components
- Fix issues in Storybook config
[CSU-108](https://fourkitchens.clickup.com/t/36718269/CSU-108)

CSU-108: Organization page

---

src/components/02-components/organization-page/organization-page.tsx
src/index.ts

- Update organization page component
[CSU-108](https://fourkitchens.clickup.com/t/36718269/CSU-108)
- Minor changes, code review only

CSU-108: Update organization page component

---

src/components/02-components/experience-time-entry-table/experience-time-entry-table.stories.tsx
src/components/02-components/experience-time-entry-table/experience-time-entry-table.tsx
src/index.ts

- Adds Time Entries by Experience Table
- https://github.com/fourkitchens/s4-app-partners/pull/5
[CSU-213](https://app.clickup.com/t/36718269/CSU-213)

CSU-213: Time Entries per Experience

---

src/components/02-components/offering-list/offering-list.stories.tsx
src/components/02-components/offering-page/offering-page.stories.tsx
src/components/02-components/offering-page/offering-page.tsx
src/components/03-layouts/page-layout/page-layout.stories.tsx
src/components/03-layouts/page-layout/page-layout.tsx
src/components/04-examples/offering/offering.stories.tsx

[CSU-159](https://fourkitchens.clickup.com/t/36718269/CSU-159)
Issues: 
- The `flex` property if affecting scroll tables in main content
- Organization selector on mobile is not working

CSU-159: add offering page example

---

src/components/02-components/card-experience-hours/card-experience-hours.tsx
src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/card-experiences-list/card-experiences-list.tsx
src/components/02-components/main-content/main-content.tsx

- Style fixes in student dashboard components
[CSU-292](https://fourkitchens.clickup.com/t/36718269/CSU-292)

CSU-292: Style fixes in student dashboard components

---

src/components/02-components/experience-time-entry-table/experience-time-entry-table.tsx

[CSU-213](https://fourkitchens.clickup.com/t/36718269/CSU-213)
- https://github.com/fourkitchens/s4-app-partners/pull/5

CSU-213: Fix table issues

---

src/components/01-elements/pager/pager.stories.tsx
src/components/01-elements/pager/pager.tsx
src/components/02-components/address-field/address-field.stories.tsx
src/components/02-components/address-field/address-field.tsx
src/components/02-components/autocomplete-field/autocomplete-field.stories.tsx
src/components/02-components/autocomplete-field/autocomplete-field.tsx
src/components/02-components/campus-list/campus-list.stories.tsx
src/components/02-components/offering-list/offering-list.stories.tsx
src/components/02-components/offering-page/offering-page.stories.tsx
src/components/02-components/offering-page/offering-page.tsx
src/components/02-components/offering-related-experiences-table/offering-related-experiences-table.stories.tsx
src/components/02-components/organization-card/organization-card.stories.tsx
src/components/02-components/organization-card/organization-card.tsx
src/components/02-components/organization-form/organization-form.stories.tsx
src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/organization-list/organization-list.stories.tsx
src/components/02-components/organization-list/organization-list.tsx
src/components/02-components/organization-page/organization-page.stories.tsx
src/index.ts

- Add components: Organization Card, Organization List, Address Field, Autocomplete Field
- Refactor pager to make pager usable when other url params are present
- Add organization form (not done yet)
[CSU-108](https://fourkitchens.clickup.com/t/36718269/CSU-108)
- Organization form is not done yet, shouldn't be tested

CSU-108: Partner onboarding / Create organization

---

src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/card-experiences-list/card-experiences-list.tsx
src/components/02-components/past-experiences-list/past-experiences-list.stories.tsx
src/components/02-components/past-experiences-list/past-experiences-list.tsx
src/index.ts
src/lib/utils.ts

- Minor fixes for Experience related components
[CSU-293](https://fourkitchens.clickup.com/t/36718269/CSU-293)

CSU-293: Students dashboard fixes

---

src/components/02-components/time-log-table/time-log-table.stories.tsx
src/components/02-components/time-log-table/time-log-table.tsx

- Add the **Time log table** component
[CSU-297](https://fourkitchens.clickup.com/t/36718269/CSU-297)

CSU-297: Time log Table component

---

src/components/02-components/offering-related-experiences-table/offering-related-experiences-table.tsx
src/components/02-components/organization-page/organization-page.tsx

- Fixes Organization's department list
- https://github.com/fourkitchens/s4-app-partners/pull/8/files

Csu demo fixes

---

src/components/02-components/card-experience/card-experience.stories.tsx
src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/experience-page/experience-page.stories.tsx
src/components/02-components/experience-page/experience-page.tsx
src/components/02-components/experiences-list/experiences-list.stories.tsx
src/components/02-components/experiences-list/experiences-list.tsx
src/index.ts

- Add new component for experience page
[CSU-296](https://fourkitchens.clickup.com/t/36718269/CSU-296)

CSU-296: Experience page

---

src/index.ts

- Export the **Time log table** component
[CSU-297](https://fourkitchens.clickup.com/t/36718269/CSU-297)

CSU-297: Export Time log Table component

---

src/components/02-components/wrapper/wrapper.stories.tsx
src/components/02-components/wrapper/wrapper.tsx
src/index.ts

- CSU-313: Partners can view their dashboard
[CSU-313: Partners can view their dashboard](https://fourkitchens.clickup.com/t/36718269/CSU-313)

feat: add wrapper component

---

src/components/02-components/experience-page/experience-page.tsx
src/components/02-components/time-log-table/time-log-table.stories.tsx
src/components/02-components/time-log-table/time-log-table.tsx

- Add pager to time log table component.
- Minor changes to the experience page.
[CSU-297](https://fourkitchens.clickup.com/t/36718269/CSU-297)

CSU-297: Add pager to time log table component

---

package-lock.json
package.json
src/components/02-components/data-table/data-table.stories.tsx
src/components/02-components/data-table/data-table.tsx
src/index.ts

feat: add data table

---

README.md
src/components/02-components/branding-bar/branding-bar.stories.tsx
src/components/02-components/branding-bar/branding-bar.tsx

- https://github.com/fourkitchens/s4-app/pull/22
- https://github.com/fourkitchens/s4-app-faculty/pull/1
- https://github.com/fourkitchens/s4-app-partners/pull/15

CSU-NOTICKET: Update branding menu

---

src/components/02-components/time-log-table/time-log-table.tsx

- Adjust time input status validation. 
[CSU-297](https://fourkitchens.clickup.com/t/36718269/CSU-297)
- https://github.com/fourkitchens/s4-app/pull/20

CSU-299: Adjust time input status validation.

---

README.md
src/components/02-components/card-basic-links/card-basic-links.stories.tsx
src/components/02-components/card-basic-links/card-basic-links.tsx
src/components/02-components/card-quick-links/card-quick-links.stories.tsx
src/components/02-components/card-quick-links/card-quick-links.tsx
src/components/02-components/offering-list/offering-list.stories.tsx
src/components/02-components/offering-list/offering-list.tsx
src/components/03-layouts/two-column-layout/two-column-layout.stories.tsx
src/components/03-layouts/two-column-layout/two-column-layout.tsx
src/index.ts

- CSU-313: Partner Dashboard
[CSU-313](https://fourkitchens.clickup.com/t/36718269/CSU-313)

CSU-313: Partner Dashboard

---

.storybook/preview.tsx
package-lock.json
package.json
scripts/link-all.sh
src/components/02-components/time-log-form/time-log-form.stories.tsx
src/components/02-components/time-log-form/time-log-form.tsx
src/components/02-components/time-log-table/time-log-table.tsx

- fix(csu-298): time entry form time changes
[CSU-298](https://fourkitchens.clickup.com/t/36718269/CSU-298)

CSU-298: Time entry form time changes

---

src/components/02-components/form/form.tsx

- fix: form item alignment
[CSU-345](https://fourkitchens.clickup.com/t/36718269/CSU-345)

fix: form item alignment

---

src/components/02-components/department-form/department-form.stories.tsx
src/components/02-components/department-form/department-form.tsx
src/index.ts

- Form Component to create a Department.
[CSU-110](https://fourkitchens.clickup.com/t/36718269/CSU-110)
- https://github.com/fourkitchens/s4-app-partners/pull/24

CSU-110: Parnert can create Departments

---

src/components/01-elements/checkbox/checkbox-input.stories.tsx
src/components/01-elements/checkbox/checkbox-input.tsx
src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/staff-assign-department/staff-assign-department.stories.tsx
src/components/02-components/staff-assign-department/staff-assign-department.tsx
src/index.ts

- Form where the Partner can edit staff members (assign department)
[CSU-318](https://fourkitchens.clickup.com/t/36718269/CSU-318)
- https://github.com/fourkitchens/s4-app-partners/pull/26

CSU-318: Partner can edit staff members (assign department)

---

src/components/02-components/campus-card/campus-card.tsx

- Modification: Text on campus list for partners.
[CSU-418](https://fourkitchens.clickup.com/t/36718269/CSU-418)

CSU-418: Modification: Text on campus list for partners.

---

src/components/02-components/address-field/address-field.tsx
src/components/02-components/autocomplete-field/autocomplete-field.tsx
src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx

[CSU-422](https://fourkitchens.clickup.com/t/36718269/CSU-422)

CSU-422: Update offering edit and create page.

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/staff-assign-role/staff-assign-role.stories.tsx
src/components/02-components/staff-assign-role/staff-assign-role.tsx
src/index.ts

- Partners can promote staff members
[CSU-413](https://fourkitchens.clickup.com/t/36718269/CSU-413)
- https://github.com/fourkitchens/s4-app-partners/pull/29

CSU-413: Partners can promote staff members

---

src/index.ts

Fix duplicate components names

---

src/components/02-components/data-table/data-table-toolbar.generic.tsx
src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/data-table/data-table.stories.tsx
src/components/02-components/data-table/data-table.tsx
src/components/02-components/staff-assign-department/staff-assign-department.stories.tsx
src/components/02-components/staff-assign-department/staff-assign-department.tsx

- Changes requested on CSU-318
[CSU-318](https://fourkitchens.clickup.com/t/36718269/CSU-318)

CSU-318: Changes requested

---

src/components/02-components/organization-form/organization-form.tsx

[CSU-395](https://fourkitchens.clickup.com/t/36718269/CSU-395)
[CSU-396](https://fourkitchens.clickup.com/t/36718269/CSU-396)
[CSU-425](https://fourkitchens.clickup.com/t/36718269/CSU-425)

CSU-395,CSU-396, CSU-425: Changes requested

---

src/components/02-components/organization-form/organization-form.stories.tsx
src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/organization-page/organization-page.stories.tsx
src/components/02-components/organization-page/organization-page.tsx
src/components/02-components/schedule-fields/schedule-fields.stories.tsx
src/components/02-components/schedule-fields/schedule-fields.tsx
src/index.ts

- Days of the week field on Organization
- Add organization address type field
[CSU-421](https://fourkitchens.clickup.com/t/36718269/CSU-421)
[CSU-504](https://fourkitchens.clickup.com/t/36718269/CSU-504)

CSU-504: Add organization address type field

---

src/components/02-components/staff-assign-role/staff-assign-role.stories.tsx
src/components/02-components/staff-assign-role/staff-assign-role.tsx

Applied requested changes from Brianna to the edit role page for staff.
[CSU-413](https://fourkitchens.clickup.com/t/36718269/CSU-413)
none

CSU-413 applying requested changes on edit roles page.

---

src/components/02-components/autocomplete-field/autocomplete-field.stories.tsx
src/components/02-components/autocomplete-field/autocomplete-field.tsx

- Taxonomy field keyword search.
[CSU-420](https://fourkitchens.clickup.com/t/36718269/CSU-420)

CSU-420: Taxonomy field keyword search

---

src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/schedule-fields/schedule-fields.tsx

[CSU-421](https://fourkitchens.clickup.com/t/36718269/CSU-421)
[CSU-504](https://fourkitchens.clickup.com/t/36718269/CSU-504)

CSU-421 | CSU-504: Fixes requested.

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/staff-archive-member/staff-archive-member.stories.tsx
src/components/02-components/staff-archive-member/staff-archive-member.tsx

Added components to archive a staff member
[CSU-319](https://fourkitchens.clickup.com/t/36718269/CSU-319)
None

CSU-319 Archive components.

---

src/components/02-components/address-field/address-field.tsx
src/components/02-components/campus-list/campus-list.tsx
src/components/02-components/context/context.tsx
src/components/02-components/organization-form/organization-form.tsx

- Fixes request in accessibility check list
none
none

fix: applied missing labels warnings

---

src/components/02-components/department-form/department-form.tsx
src/theme/index.ts

- Added form validation to required inputs in form edit department.
[CSU-507](https://fourkitchens.clickup.com/t/36718269/CSU-507)
none

CSU-507 Added form validation

---

src/components/02-components/department-form/department-form.tsx

- Fixing form validation
CSU-507
none

Fix: changes form validation in deparment form

---

src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx

- Offering edit "expected skill acquisition"
- Offering edit "Safety Considerations"
[CSU-447](https://fourkitchens.clickup.com/t/36718269/CSU-447)
[CSU-449](https://fourkitchens.clickup.com/t/36718269/CSU-449)

CSU-449|CSU-449: Offering new fields

---

src/components/02-components/autocompletes-dependecy-fields/autocompletes-dependecy-fields.stories.tsx
src/components/02-components/autocompletes-dependecy-fields/autocompletes-dependecy-fields.tsx
src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx
src/index.ts

- Offering edit page preferred and required language
[CSU-443](https://fourkitchens.clickup.com/t/36718269/CSU-443)

WIP CSU-443: Offering edit page preferred and required language

---

src/components/02-components/department-form/department-form.stories.tsx
src/components/02-components/department-form/department-form.tsx
src/components/02-components/organization-page/organization-page.tsx

- Updated department form component.
CSU-436
- none
none

feat: CSU-436 updated department form

---

src/components/02-components/department-form/department-form.tsx

minor fixed added attribute type to delete department button.
CSU-437

fix: added type to delete button

---

src/components/02-components/address-field/address-field.tsx
src/components/02-components/autocompletes-dependecy-fields/autocompletes-dependecy-fields.stories.tsx
src/components/02-components/autocompletes-dependecy-fields/autocompletes-dependecy-fields.tsx
src/components/02-components/branding-bar/branding-bar.tsx
src/components/02-components/campus-list/campus-list.tsx
src/components/02-components/context/context.tsx
src/components/02-components/department-delete/department-delete.stories.tsx
src/components/02-components/department-delete/department-delete.tsx
src/components/02-components/department-form/department-form.stories.tsx
src/components/02-components/department-form/department-form.tsx
src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/organization-page/organization-page.tsx
src/components/02-components/staff-archive-member/staff-archive-member.tsx
src/index.ts
src/theme/index.ts

-  added form variable.
- 
[CSU-319](https://fourkitchens.clickup.com/t/36718269/CSU-319)
- none
none

feat: csu319 added form variable.

---

src/components/02-components/offering-form/offering-form.tsx

[CSU-449](https://fourkitchens.clickup.com/t/36718269/CSU-449)

CSU-449: fixes requested on offering node

---

src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx

- Offering edit "Location Type"
[CSU-448](https://fourkitchens.clickup.com/t/36718269/CSU-448)

CSU-448: Offering edit Location Type

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/data-table/data-table.stories.tsx
src/components/04-pages/generic/data-table-page.stories.tsx
src/components/04-pages/generic/data-table-page.tsx

- Added membership requested data table in staff page.
CSU-508
none

feat: csu-508 added membership requested data table

---

src/index.ts

- just added a new line to `index.ts`
CSU-508
- none
none

feat: csu-508 added to index.ts.

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/membership-request/membership-request.stories.tsx
src/components/02-components/membership-request/membership-request.tsx
src/index.ts

- added CSU-508 memberships requested confirmation page
CSU-508

feat(csu-508): added confirmation page

---

package-lock.json
package.json

[CSU-506](https://fourkitchens.clickup.com/t/36718269/CSU-506)

CSU-506: Security vulnerability report in GitHub

---

src/components/02-components/data-table/data-table.data.tsx

- Fixes requested.
[CSU-319](https://fourkitchens.clickup.com/t/36718269/CSU-319)

CSU-319: fixes requested.

---

src/components/02-components/organization-card/organization-card.tsx
src/components/03-layouts/page-layout/page-layout.tsx

- Applying requested changes for onboarding and skip to main content button.
CSU-395
- none
> The join request ('Select' button) should lead to a confirmation dialog so that partners do not accidentally request to join an organization they do not belong to with an accidental click. 
none

CSU-395 Applying requested changes for onboarding

---

src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/participation-requirements/participation-requirements.stories.tsx
src/components/02-components/participation-requirements/participation-requirements.tsx
src/components/02-components/schedule-fields/schedule-fields.tsx
src/index.ts

- Added participation requirements fields and updated offering form.
CSU-445
- none
- none

CSU-445 Added participation requirements fields

---

src/components/04-pages/generic/data-table-page.stories.tsx
src/components/04-pages/generic/data-table-page.tsx
src/components/04-pages/generic/invite-staff-dialog.tsx

Invite members logic.
CSU-309
load the organization page in storybook and hit the invite button.
none

feat(csu-309): added invite modal

---

src/components/02-components/steps-bar/steps-bar.tsx
src/components/02-components/student-experience-form-step3/student-experience-form-step3.tsx
src/components/02-components/student-experience-form-step4/student-experience-form-step4.stories.tsx
src/components/02-components/student-experience-form-step4/student-experience-form-step4.tsx
src/index.ts

- Added approval step 4 for create experiences form.
- Added some modification for step 3 to improve the data managment.
[CSU-303](https://fourkitchens.clickup.com/t/36718269/CSU-303)
none

feat(csu-303): Added approval step form

---

src/components/00-tokens/icon/material/material-icons.stories.tsx
src/components/02-components/student-experience-form-step5/student-experience-form-step5.tsx
src/components/02-components/student-experience-form-step6/student-experience-form-step6.stories.tsx
src/components/02-components/student-experience-form-step6/student-experience-form-step6.tsx
src/index.ts

- Added step 5 summary screen.
- Updated components index.
[CSU-514](https://fourkitchens.clickup.com/t/36718269/CSU-514)
- none

Added summary step 5 summary page

---

src/components/02-components/student-experience-form-step5/student-experience-form-step5.stories.tsx
src/components/02-components/student-experience-form-step5/student-experience-form-step5.tsx
src/components/02-components/student-experience-form-step6/student-experience-form-step6.tsx

- Added error message for duration step in creating experience form.
[CSU-207](https://fourkitchens.clickup.com/t/36718269/CSU-207)
- none
none

feat(csu-207): Added error message

---

src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx

- FIX: Offering edit fields Time Commitment and Compensation in partner app
[CSU-516](https://fourkitchens.clickup.com/t/36718269/CSU-516)

CSU-515: Fix on Offering edit fields.

---

src/components/02-components/program-card/program-card.tsx
src/components/02-components/program-list/program-list.tsx
src/components/02-components/program-page/program-page.tsx

- Updated programs files to enhance the use of `MaterialUI`.
- Added Autocomplete input to search by program title.
[CSU-433](https://fourkitchens.clickup.com/t/36718269/CSU-433)
- none
none

feat(csu-433): Added program name search input

---

src/components/02-components/branding-bar/branding-bar.tsx
src/components/02-components/card-basic-links/card-basic-links.tsx
src/components/02-components/card-quick-links/card-quick-links.tsx
src/components/02-components/context/context.tsx
src/components/02-components/offering-card/offering-card.tsx
src/components/02-components/stat-with-icon/stat-with-icon.stories.tsx
src/components/02-components/stat-with-icon/stat-with-icon.tsx
src/components/02-components/wrapper/wrapper.tsx
src/components/03-layouts/two-column-layout/two-column-layout.tsx

- Added missing aria labels to patch accessibility issues.
- Refactor some layout using `Stack` from MaterialUI to improve the responsiveness.
none - working based on `6_28_CUDA S4 Partner App Accessibility Eval`
- none
none

fix: enhancing accessibility and responsiveness

---

src/components/01-elements/logo/logo.tsx
src/components/01-elements/sidebar-toggle/sidebar-toggle.tsx
src/components/02-components/brand/brand.tsx
src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/offering-card/offering-card.tsx
src/components/03-layouts/page-layout/page-layout.tsx
src/components/04-pages/generic/data-table-page.tsx
src/components/04-pages/generic/invite-staff-dialog.tsx

- Working on fixing accessibility issues.
none
- none
- none
none

fix: enhancing accessibility.

---

src/components/02-components/offering-list/offering-list.tsx

Working on accessibility issues from latest evaluation `6_28_CUDA S4 Partner App Accessibility Eval`

fix: added aria labels for accessibility

---

src/components/02-components/autocomplete-field/autocomplete-field.tsx
src/components/02-components/autocompletes-dependecy-fields/autocompletes-dependecy-fields.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/organization-form/organization-form.tsx
src/components/02-components/student-experience-form-step2/student-experience-form-step2.tsx
src/components/02-components/tabs/tabs.tsx
src/components/02-components/time-log-form/time-log-form.tsx
src/components/02-components/user-profile-form/user-profile-form.tsx

- Applied some changes to improve the accesibility.
No tickets, work is being tracking [here](https://thecsu.sharepoint.com/:x:/r/sites/CSUCO-CalStateS4Transition/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B9a503597-30a1-47ac-ba99-108b09f4cb5c%7D&wdOrigin=TEAMS-WEB.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1720879662146&web=1)
- None
- None
None

Fixes related with accessibility in offering form

---

src/components/02-components/opportunity-card/opportunity-card.tsx

- Remove approved state
[CSU-535]
- pull
N/A

CSU-535: Remove approved state

---

src/components/02-components/opportunity-card/opportunity-card.tsx

- Add ? to approvalState value
[CSU-535](https://fourkitchens.clickup.com/t/36718269/CSU-XX)

CSU-535: Add ? to approvalState value

---

src/components/02-components/data-table/data-table.data.tsx
src/components/04-pages/generic/data-table-page.stories.tsx
src/components/04-pages/generic/data-table-page.tsx

- Added check icon and fixed some link form data table button.
CSU-524 Partners can access an "Approve Experience(s)" page listing the experiences waiting to be approved
- npm run dev
none

CSU-524: Added approve experiences button in experiences page.

---

src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/organization-form/organization-form.tsx

- Update forms submit functionality for smooth scroll
CSU-531:  Add messages and field validation to required fields in FE Offering and Organization forms
- pull

CSU-531: Update forms submit functionality for smooth scroll

---

src/components/02-components/student-experience-form/student-experience-form.tsx

- Text correction
CSU-549: Create a warning if there is already an experience created with that opportunity with this user in the first step of experience creation.

CSU-549: Text correction

---

src/components/02-components/address-field/address-field.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/organization-form/organization-form.tsx

-  Solve all issues of ticket csu-531
CSU-531: Add messages and field validation to required fields in FE Offering and Organization forms

CSU-531: Solve all issues of ticket csu-531

---

src/lib/utils.ts

- Update experience status with new flow
CSU-547: Update experience query to receive all experiences related to the user regardless of the status.

CSU-547: Update experience status with new flow

---

src/components/02-components/autocomplete-field/autocomplete-field.tsx
src/components/02-components/card-experience/card-experience.stories.tsx
src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/student-experience-form-step2-update/student-experience-form-step2-update.stories.tsx
src/components/02-components/student-experience-form-step2-update/student-experience-form-step2-update.tsx
src/components/02-components/student-experience-form-step3/student-experience-form-step3.tsx
src/components/02-components/student-experience-form-step4/student-experience-form-step4.tsx
src/components/02-components/student-experience-form-step5/student-experience-form-step5.tsx
src/components/02-components/student-experience-form-step6/student-experience-form-step6.tsx
src/index.ts
src/lib/utils.ts

- All changes needed to make experience no workflow
CSU-550: Create an Update Experience workflow in the Student FE
- Pull

CSU-550: All changes needed to make experience no workflow

---

src/components/02-components/student-experience-form-step3/student-experience-form-step3.tsx

Csu-528: Add comments to step 3

---

src/components/02-components/program-card/program-card.tsx

[CSU-517](https://fourkitchens.clickup.com/t/36718269/CSU-517)

CSU-517: Bug: Program apply is stuck in pending

---

src/components/02-components/opportunity-list/opportunity-list.tsx

CSU-560: Add category filter

---

src/components/02-components/time-log-form/time-log-form.tsx

CSU-562: Add field related to learning outcomes functionality

---

src/components/02-components/time-log-form/time-log-form.tsx

- Add new fields need for TPEs

CSU-562: Add new fields need for TPEs

---

package-lock.json
package.json
src/components/02-components/map/map.stories.tsx
src/components/02-components/map/map.tsx
src/index.ts

- Add map component to library

CSU-571: Add map component to library

---

src/components/02-components/map/map.tsx

CSU-571: Finish map changes V2

---

src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/student-experience-form-step6/student-experience-form-step6.tsx
src/lib/utils.ts

CSU-569: Add two weeks editing

---

src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/offering-page/offering-page.tsx

- add application period to offerings

CSU-525: add application period to offerings

---

src/components/02-components/organization-faculty-list/organization-faculty-list.stories.tsx
src/components/02-components/organization-faculty-list/organization-faculty-list.tsx
src/index.ts

- Add filtering component to organization page

CSU-329: Add filtering component to organization page

---

src/components/02-components/map/map.tsx

- Null exceptions added to latitude longitude

CSU-370: Null exceptions added to latitude longitude

---

src/components/02-components/organization-faculty-card/organization-faculty-card.stories.tsx
src/components/02-components/organization-faculty-card/organization-faculty-card.tsx
src/components/02-components/organization-faculty-list/organization-faculty-list.tsx

- Correction to props and card in exception case

CSU-332: Correction to props and card in exception case

---

src/components/02-components/organization-faculty-list/organization-faculty-list.stories.tsx
src/components/02-components/organization-faculty-list/organization-faculty-list.tsx

CSU-332: Correction of errors on list

---

src/components/02-components/organization-faculty-page/organization-faculty-page.stories.tsx
src/components/02-components/organization-faculty-page/organization-faculty-page.tsx
src/index.ts

- Add single page of organizations component

CSU-331: Add single page of organizations component

---

src/components/02-components/map/map.tsx
src/components/02-components/opportunity-card/opportunity-card.tsx
src/components/02-components/opportunity-page/opportunity-page.tsx

- Add facultyUrl case for opportunities

CSU-333: Add facultyUrl case for opportunities

---

src/components/04-pages/partners/organization/experiences/experience-details/experience-details.tsx

- Remvove color to make sure it works

CSU-567: Remvove color to make sure it works

---

src/components/02-components/map/map.tsx
src/components/02-components/opportunity-card/opportunity-card.tsx
src/components/02-components/opportunity-page/opportunity-page.tsx
src/components/02-components/student-experience-form/student-experience-form.stories.tsx

- Add structure for add to course button

CSU-344: Add structure for add to course button

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/data-table/data-table.tsx
src/components/02-components/faculty-time-log-table/faculty-time-log-table.stories.tsx
src/components/02-components/faculty-time-log-table/faculty-time-log-table.tsx
src/components/04-pages/faculty/experiences/experience-details/experience-details.stories.tsx
src/components/04-pages/faculty/experiences/experience-details/experience-details.tsx
src/index.ts

- Add all styling needed for experience page

CSU-360: Add all styling needed for experience page

---

src/components/02-components/autocomplete-field-no-dropdown/autocomplete-field-no-dropdown.stories.tsx
src/components/02-components/autocomplete-field-no-dropdown/autocomplete-field-no-dropdown.tsx
src/components/02-components/opportunity-list/opportunity-list.tsx
src/components/02-components/organization-faculty-page/organization-faculty-page.tsx
src/index.ts

- Add new field needed for organization filtering

CSU-363: Add new field needed for organization filtering

---

src/components/02-components/data-table/data-table.data.tsx

- Add aria label to focus table

CSU-527: Add aria label to focus table

---

src/components/02-components/address-field/address-field.tsx
src/components/02-components/offering-form/offering-form.tsx

- Corrections to offering form for coordinates

CSU-580: Corrections to offering form for coordinates

---

src/components/02-components/autocomplete-field-no-dropdown/autocomplete-field-no-dropdown.tsx
src/components/02-components/campus-card/campus-card.tsx
src/components/02-components/offering-form/offering-form.stories.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/students-information/students-information.stories.tsx
src/components/02-components/students-information/students-information.tsx
src/index.ts

- All changes needed for new offering form fields

CSU-444: All changes needed for new offering form fields

---

src/components/02-components/autocomplete-field-no-dropdown/autocomplete-field-no-dropdown.tsx
src/components/02-components/offering-form/offering-form.tsx
src/components/02-components/opportunity-list/opportunity-list.tsx

- Solve issue of no dropdown field only id needed

CSU-444: Solve issue of no dropdown field only id needed

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/student-experience-form-step4/student-experience-form-step4.tsx
src/lib/utils.ts

- Finish corrections for approval process

CSU-588: Finish corrections for approval process

---

src/components/02-components/course-card/course-card.stories.tsx
src/components/02-components/course-card/course-card.tsx
src/components/02-components/course-list/course-list.stories.tsx
src/components/02-components/course-list/course-list.tsx
src/index.ts

- Add new course manage components

CSU-581: Add new course manage components

---

src/components/02-components/card-experience/card-experience.tsx
src/components/02-components/experience-page/experience-page.tsx

CSU-590: Correction to experience components

---

src/components/02-components/data-table/data-table.data.tsx

csu-527: add columns screen readers text

---

src/components/02-components/data-table/data-table.data.tsx
src/components/02-components/experience-deny/experience-deny.stories.tsx
src/components/02-components/experience-deny/experience-deny.tsx
src/index.ts

- CSU-536: functionality to deny experience

CSU-536: functionality to deny experience
